[tool.poetry]
name = "masadora"
version = "0.1.0"
description = ""
authors = ["Aravind Pai <dragondive@outlook.in>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
minimal = "^0.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
