name: Update PlantUML diagram from external data
on:
  workflow_dispatch:

jobs:
  land-helicopter:
    name: Generate PlantUML diagram
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-22.04
          - windows-2022
          - windows-2019
          - macos-14
          - macos-13
        plantuml-version:
          - latest
          - '1.2024.6'
          - '1.2024.5'
        cli-arguments:
          - '-h'
          - '-decodeurl https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuNBAJrBGjLDmpCbCJbMmKiX8pSd9vt98pKi1IW80'
          - '-tsvg plantuml/production_controller_sequence.puml'
        jvm-options:
          - ''
          - '-DPLANTUML_LIMIT_SIZE=8192'
          - '-Xmx1024m'
          - '-DPLANTUML_LIMIT_SIZE=8192 -Xmx1024m'

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Run PlantUML
        uses: dragondive/run-plantuml-local@main
        with:
          version: ${{ matrix.plantuml-version }}
          cli-arguments: ${{ matrix.cli-arguments }}
          jvm-options: ${{ matrix.jvm-options }}
