name: Test snok/install-poetry
on: 
  workflow_dispatch

jobs:
  placeholder:
    name: >
      Placeholder in main branch to enable workflow_dispatch 
      in snok-install-poetry-tests branch
    runs-on: ubuntu-latest

    steps:
      - name: Nothing
        shell: bash
        run: |
          echo "This is a placeholder job in the main branch."
